CREATE DATABASE angular_auth;

USE angular_auth;

CREATE TABLE users
(
  id INT(11) PRIMARY KEY NOT NULL
  AUTO_INCREMENT,
  name VARCHAR
  (50) NOT NULL,
  email VARCHAR
  (20) NOT NULL UNIQUE,
  password VARCHAR
  (255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  url_id VARCHAR(255) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;